const crypto = require('node:crypto');

// Storage keys are ALWAYS generated by the server: users/<userId>/<random-uuid>.<pdf|docx|txt>
// No part of a key ever comes from a filename, path or id supplied by a client, and every storage
// operation re-validates the key against this exact shape, so ".." segments, absolute paths, other
// users' folders or odd characters can never be expressed.

const UUID = '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}';
const KEY_PATTERN = new RegExp(`^users/(${UUID})/(${UUID})\\.(pdf|docx|txt)$`);
const EXTENSIONS = { PDF: 'pdf', DOCX: 'docx', TXT: 'txt' };

function buildKey(userId, fileType) {
  const ext = EXTENSIONS[fileType];
  if (!ext) throw new Error('Unsupported file type.');
  if (!new RegExp(`^${UUID}$`).test(userId)) throw new Error('Invalid user id.');
  return `users/${userId}/${crypto.randomUUID()}.${ext}`;
}

// Returns { userId, name } for a well-formed key, or null.
function parseKey(key) {
  if (typeof key !== 'string' || key.length > 120) return null;
  const m = KEY_PATTERN.exec(key);
  return m ? { userId: m[1], name: `${m[2]}.${m[3]}` } : null;
}

const isValidKey = (key) => parseKey(key) !== null;

module.exports = { buildKey, parseKey, isValidKey };
